# example netlify.toml
[dev]
    command = "yarn serve"

[build]
  command = "yarn build"
  functions = "functions/" #  netlify-lambda reads this
  publish = "dist"

# [[redirects]]
#   from = "/faucet/:address"
#   to = "/.netlify/functions/faucet?address=:address"
#   status = 200

[[redirects]]
 from = "/faucet"
 to = "/.netlify/functions/faucet"
 status = 200

# [[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200
